/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ikjlnyzhunmsqixxdsxw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlramxueXpodW5tc3FpeHhkc3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQyMjM4OTcsImV4cCI6MjA5OTc5OTg5N30.EU6trvfooRtc-Kb9FnUVaBilfpWQxnbTs3WAQh0-WK4"